CC=clang
CFLAGS=-Wall -g -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer

all: Ex2 Ex3 Ex4 Ex5 Ex6

Ex2:
	$(CC) Ex2.c $(CFLAGS)

Ex3:
	$(CC) Ex3.c $(CFLAGS) 

Ex4:
	$(CC) Ex4.c $(CFLAGS) 

Ex5:
	$(CC) Ex5.c $(CFLAGS) 

Ex6:
	$(CC) Ex6.c $(CFLAGS) 
